Website = "https://github.com/fourcourtjester/single-studio-gamestate"

[Details]
Icon = "Icon.png"
Name = "Single Studio - GameState"
ID = "com.singlestudio.gamestate"
Version = "0.1.0"
Build = 3

[Release]
BuildName = "gamestate"
